---
apiVersion: v1
kind: Service
metadata:
  annotations:
    znodekube.version: "10.0"
  creationTimestamp: null
  labels:
    app: znode10xcodeeditorui-app
  name: znode10xcodeeditorui
spec:
  ports:
    - name: "443"
      port: 443
      targetPort: 443 
  type: LoadBalancer
  selector:
    app: znode10xcodeeditorui-app
status:
  loadBalancer: {}

--- 

