---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubernetes-service.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    app: znode10xcodeeditorui-app
  name: znode10xcodeeditorui
spec:
  ports:
    - name: "443"
      port: 443
      targetPort: 443 
  type: LoadBalancer
  selector:
    app: znode10xcodeeditorui-app
status:
  loadBalancer: {}

--- 
