name: Azure SQL DB Access

on:

 workflow_dispatch:
  inputs:
    # environment:
    #   description: Environment Name
    #   required: true
    sql_server_name:
      description: DB Server Name (db-abcd-ep.database.windows.net)
      required: true
    db_name:
      description: DB Name to execute query on (wbst_qa)
      required: true
    db_user:
      description: DB User Name (write access)
      required: true
    db_password:
      description: DB Password (write access)
      required: true


jobs:
  execute-sql:
    runs-on: ubuntu-latest
    # environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}

    - name: Install SQLCMD
      run: |
        sudo apt-get update
        sudo apt-get install -y mssql-tools unixodbc-dev
        echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
        source ~/.bashrc

    - name: Install SQLCMD
      run: |
        sudo apt-get update
        sudo apt-get install -y mssql-tools unixodbc-dev
        echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
        source ~/.bashrc

    - name: Execute Shell Script
      run: |
        chmod +x shellscript/domain_entries.sh
        ./shellscript/domain_entries.sh
      env:
        AZURE_SQL_SERVER: ${{ inputs.sql_server_name }}
        AZURE_SQL_DB: ${{ inputs.db_name }}
        AZURE_SQL_USER: ${{ inputs.db_user }}
        AZURE_SQL_PASSWORD: ${{ inputs.db_password }}
