name: Local DB build & deploy

on:
  workflow_dispatch:
    inputs:
      local_server:
        description: 'Local database server name'
        required: true
        default: 'localhost'

      mtft_db_name:
        description: 'Multifront database name'
        required: true
        default: 'z10_wbst_dev'

      local_db_uname:
        description: 'Database username'
        required: true
        default: 'sa'

      local_db_passwd:
        description: 'Database password'
        required: true
        default: 'yourStrong(!)Password'

      multifront_db:
        description: "Build Multifront DB"
        required: true
        default: false
        type: boolean

        
      db_number:
        description: database build number
        required: true

jobs:

  build_multifront_db:
    runs-on: windows-latest
    if: ${{ github.event.inputs.multifront_db == 'true' }}

    steps:

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}

      - name: Download the mutlifront dacpac
        run: |
          az storage file download --path Znode_Multifront_Database_${{ inputs.db_number }}.dacpac --dest .\dacpac\ --share-name multifront-dacpac --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          az storage file download --path master_${{ inputs.db_number }}.dacpac --dest .\dacpac\ --share-name multifront-dacpac --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} 
          dir .\dacpac\


          
        
      - name: Copy DACPACs to flat folder
        run: |
          mkdir dacpac-out
          copy dacpac\Znode_Multifront_Database_${{ inputs.db_number }}.dacpac dacpac-out\Znode_Multifront_Database.dacpac
          copy dacpac\master_${{ inputs.db_number }}.dacpac dacpac-out\master.dacpac          
      - name: Upload DACPAC Artifacts (flat)
        uses: actions/upload-artifact@v4
        with:
          name: multifront-dacpac
          path: dacpac-out
          
  deploy_multifront_db:
    runs-on: [self-hosted, Linux, X64, db_deploy_on_194]
    needs: build_multifront_db
    if: ${{ github.event.inputs.multifront_db == 'true' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Download Multifront DACPAC Artifact
        uses: actions/download-artifact@v4
        with:
          name: multifront-dacpac
          path: ./dacpac

      - name: Deploy Multifront DB
        env:
          DACPAC_FILE: "${{ github.workspace }}/dacpac/Znode_Multifront_Database.dacpac"
          MASTER_DACPAC: "${{ github.workspace }}/dacpac/master.dacpac"
          DB_SERVER: ${{ inputs.local_server }}
          DB_NAME: "${{ github.event.inputs.mtft_db_name }}"
          DB_USER: ${{ inputs.local_db_uname }}
          DB_PASS: ${{ inputs.local_db_passwd }}
        run: |
          echo "Deploying $DACPAC_FILE to $DB_NAME"
          /opt/sqlpackage/sqlpackage /Action:Publish \
            /SourceFile:"$DACPAC_FILE" \
            /TargetConnectionString:"Server=$DB_SERVER;Database=$DB_NAME;User Id=$DB_USER;Password=$DB_PASS;Encrypt=False;TrustServerCertificate=True;" \
            /p:BlockOnPossibleDataLoss=false \
            /p:AdditionalDeploymentContributorArguments="/p:ReferencePath=$(dirname $MASTER_DACPAC)"