name: Deploy DB on Tenants
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: Enter Environment Name 
        required: true
        
      deploy_multifront_db:
        description: 'Build Multifront DB'
        required: true
        default: false
        type: boolean


      deploy_hgfr_db:
        description: 'Build Hangfire DB'
        required: true
        default: false
        type: boolean

      deploy_rceg_db:
        description: 'Build Recommendation DB'
        required: true
        default: false
        type: boolean

      deploy_paymnt_db:
        description: 'Build Pymt Mngr DB'
        required: true
        default: false
        type: boolean

        
      db_number:
        description: database build number
        required: true

jobs:
  deploy_hgfr_db:
    if: ${{ github.event.inputs.deploy_hgfr_db == 'true' }}  
    name: Deploy hangfire Databases 
    runs-on: windows-2022
    environment: ${{ github.event.inputs.environment }}
    steps:

      # Login using Azure credentials
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}

      - name: Download the hangfire dacpac
        run: |
          az storage file download --path Znode_Multifront_Hangfire_Database_${{ inputs.db_number }}.dacpac --dest .\dacpac\ --share-name hangfire-dacpac --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} 
          dir .\dacpac\

      - name: Azure SQL Deploy
        uses: Azure/sql-action@v1
        with:
          # Name of the SQL Server
          server-name: ${{ secrets.DB_SERVER_NAME }}

      # The connection string, including authentication information for the Azure SQL Database 
          connection-string: '${{ secrets.HANGFIRE_DB_CONNECTION_STRING }}'

      # Path to the dacpac file
          dacpac-package: .\dacpac\Znode_Multifront_Hangfire_Database_${{ inputs.db_number }}.dacpac

      # Additional arguments 
          arguments: '/p:BlockOnPossibleDataLoss=false /p:DropObjectsNotInSource=false'

      # Specify target platform version (adjust as needed)
#          target-platform-version: 'v12.0'

      # Database name provided directly here
#          database-name: 'hgfr_z10'

#########################################################################################################################################
  deploy_multifront_db:
    if: ${{ github.event.inputs.deploy_multifront_db == 'true' }}
    name: Deploy multifront Databases 
    runs-on: windows-2022
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Download the mutlifront dacpac
        run: |
          az storage file download --path Znode_Multifront_Database_${{ inputs.db_number }}.dacpac --dest .\dacpac\ --share-name multifront-dacpac --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} 
          dir .\dacpac\

      - name: Azure SQL Deploy
        uses: Azure/sql-action@v1
        with:
          # Name of the SQL Server
          server-name: ${{ secrets.DB_SERVER_NAME }}

      # The connection string, including authentication information for the Azure SQL Database 
          connection-string: '${{ secrets.MULTIFRONT_DB_CONNECTION_STRING }}'

      # Path to the dacpac file
          dacpac-package: .\dacpac\Znode_Multifront_Database_${{ inputs.db_number }}.dacpac

      # Additional arguments 
          arguments: '/p:BlockOnPossibleDataLoss=false /p:DropObjectsNotInSource=false'

      # Specify target platform version (adjust as needed)
#          target-platform-version: 'v12.0'
          
      # Database name provided directly here
#          database-name: 'wbst_z10'
        
#######################################################################################################################################
  deploy_paymnt_db:
    if: ${{ github.event.inputs.deploy_paymnt_db == 'true' }}  
    name: Deploy pymnt Databases 
    runs-on: windows-2022
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Download the Plugin Payment dacpac
        run: |
          az storage file download --path Znode_Multifront_Plugin_Payment_${{ inputs.db_number }}.dacpac --dest .\dacpac\ --share-name payment-dacpac --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} 
          dir .\dacpac\

      - name: Azure SQL Deploy
        uses: Azure/sql-action@v1
        with:
          # Name of the SQL Server
          server-name: ${{ secrets.DB_SERVER_NAME }}

      # The connection string, including authentication information for the Azure SQL Database 
          connection-string: '${{ secrets.PAYMT_MNGR_DB_CONNECTION_STRING }}'

      # Path to the dacpac file
          dacpac-package: .\dacpac\Znode_Multifront_Plugin_Payment_${{ inputs.db_number }}.dacpac

      # Additional arguments 
          arguments: '/p:BlockOnPossibleDataLoss=false /p:DropObjectsNotInSource=false'

      # Specify target platform version (adjust as needed)
#          target-platform-version: 'v12.0'

      # Database name provided directly here
#          database-name: 'pymt_z10'

##############################################################################################################################################

  deploy_rceg_db:
    if: ${{ github.event.inputs.deploy_rceg_db == 'true' }}  
    name: Deploy rceg Databases 
    runs-on: windows-2022
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Download the Recommendation dacpac
        run: |
          az storage file download --path Znode_Multifront_RecommendationEngine_Database_${{ inputs.db_number }}.dacpac --dest .\dacpac\ --share-name rceg-dacpac --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} 
          dir .\dacpac\

      - name: Azure SQL Deploy
        uses: Azure/sql-action@v1
        with:
          # Name of the SQL Server
          server-name: ${{ secrets.DB_SERVER_NAME }}

      # The connection string, including authentication information for the Azure SQL Database 
          connection-string: '${{ secrets.RCEG_DB_CONNECTION_STRING }}'

      # Path to the dacpac file
          dacpac-package: .\dacpac\Znode_Multifront_RecommendationEngine_Database_${{ inputs.db_number }}.dacpac

      # Additional arguments 
          arguments: '/p:BlockOnPossibleDataLoss=false /p:DropObjectsNotInSource=false'

      # Specify target platform version (adjust as needed)
#          target-platform-version: 'v12.0'

      # Database name provided directly here
#          database-name: 'rceg_z10'

#############################################################################################################
