name: Import BACPAC to Remote SQL Server

on:
  workflow_dispatch:
    inputs:
      db_name:
        description: 'Target database name'
        required: true
      bacpac_name:
        description: 'Name of the .bacpac file'
        required: true
      storage_account:
        description: 'Azure Storage Account Name'
        required: true
      container_name:
        description: 'Blob Container Name'
        required: true
      target_sql_host:
        description: 'Target SQL Server IP'
        required: true
      db_password:
        description: 'SQL Server Password'
        required: true
        type: string
      runner_label:
        description: 'Runner label'
        required: true

jobs:
  import_bacpac:
    name: Import BACPAC
    runs-on: ${{ github.event.inputs.runner_label }}

    steps:
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Download BACPAC from Azure Blob Storage
        env:
          AZURE_STORAGE_ACCOUNT: ${{ github.event.inputs.storage_account }}
          AZURE_STORAGE_KEY_VM: ${{ secrets.AZURE_STORAGE_KEY_VM }}
        run: |
          mkdir -p ./bacpac
          echo "Downloading BACPAC..."
          az storage blob download \
            --account-name "$AZURE_STORAGE_ACCOUNT" \
            --account-key "$AZURE_STORAGE_KEY_VM" \
            --container-name "${{ github.event.inputs.container_name }}" \
            --name "${{ github.event.inputs.bacpac_name }}" \
            --file "./bacpac/${{ github.event.inputs.bacpac_name }}"

      - name: Check or Install sqlpackage
        run: |
          if [ ! -f /opt/sqlpackage/sqlpackage ]; then
            echo "sqlpackage not found. Installing..."
            curl -L -o sqlpackage.zip https://aka.ms/sqlpackage-linux
            unzip -o sqlpackage.zip -d sqlpackage
            chmod +x sqlpackage/sqlpackage
            sudo mkdir -p /opt/sqlpackage
            sudo mv sqlpackage/* /opt/sqlpackage/
          else
            echo "sqlpackage already installed. Skipping installation."
          fi

      - name: Import BACPAC into Remote SQL Server
        env:
          DB_USER: ${{ secrets.DB_USER }}
        run: |
          echo "Importing database '${{ github.event.inputs.db_name }}' to '${{ github.event.inputs.target_sql_host }}'"
          /opt/sqlpackage/sqlpackage /Action:Import \
            /SourceFile:"./bacpac/${{ github.event.inputs.bacpac_name }}" \
            /TargetConnectionString:"Server=${{ github.event.inputs.target_sql_host }},1433;Database=${{ github.event.inputs.db_name }};User Id=$DB_USER;Password=${{ github.event.inputs.db_password }};Encrypt=True;TrustServerCertificate=True;" \
            /p:DatabaseEdition=Standard \
            /p:DatabaseServiceObjective=S1