name: Restart Etna Production

on:
 schedule:
    - cron: '0 7 * * *'  # 4:00 AM UTC = 9:30 AM IST
 workflow_dispatch:

jobs:
  download_stage_restore_backup:
    runs-on: ubuntu-22.04
    environment: etnapr

    steps:

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}
        
    - name: Set up Kubeconfig
      run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config        
      shell: bash
        
    - name: Restart Deployments
      run: |
         echo "Restarting deployments in namespace 'znode' in batches..."
         
         # Namespace
         NS=znode
         
         # Ordered deployment batches (in groups of 3)
         batches=(
           "znode10apicp znode10customapi znode10xadmin"
           "znode10xapi znode10xapiv2 znode10xazfunctions"
           "znode10xcustomtable znode10xpagebuilder znode10xpaymentmanager"
           "znode10xpluginbraintree znode10xpluginfedex znode10xpluginspreedly"
           "znode10xpluginups znode10xreports znode10xshippingmanager znode10xwebstore"
         )
         
         # Restart each batch with a 120-second pause
         for batch in "${batches[@]}"; do
           for deployment in $batch; do
             echo "Restarting $deployment"
             kubectl rollout restart deployment/$deployment -n $NS
           done
         echo "Sleeping 120 seconds before next batch..."
         sleep 120
         done
         
         # Restart gateways last
         echo "Restarting gateways: znode10xapigateways"
         kubectl rollout restart deployment/znode10xapigateways -n $NS         
         echo "Restart process complete."

