name: Schedule Re-creating Knox and Etna qa 

on:
  # push:
  #   branches:
  #     - DEV-935-pipeline-for-etna-knox-qa
  schedule:
    - cron: "45 17 * * 1-5"
jobs:
  trigger_recreate_pods:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Etna QA Re-creation
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.ACCESS_REPO }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/MRRSoft/znode10-tenant-devops/actions/workflows/re-create_all_tenant_qa.yml/dispatches \
            -d '{
              "ref": "master",
              "inputs": {
                "environment": "etnaqa",
                "restart_all": true,
                "pods_restart_all": true
              }
            }'

      - name: Trigger Knox QA Re-creation
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.ACCESS_REPO }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/MRRSoft/znode10-tenant-devops/actions/workflows/re-create_all_tenant_qa.yml/dispatches \
            -d '{
              "ref": "master",
              "inputs": {
                "environment": "knoxqa",
                "restart_all": true,
                "pods_restart_all": true
              }
            }'
