name: AMLA.IO Domain SSL Renewal

on:
 workflow_dispatch:
    inputs:
        environment:
            type: choice
            description: select the environment
            required: true
            options:
              - etnapr
              - etnaqa
              - uat
              - sandbox
              - etnadev
              - knoxdev
              - demostage

        # select_env_path:
        #         type: choice
        #         description: Select env path
        #         options:
        #           - tenants/uat
        #           - tenants/usds
        #           - tenants/etna/dev
        #           - tenants/knox/dev

jobs:
  ssl_renew:
    name: Amla.IO Domain SSL
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:

      - name: Set environment path
        id: set-path
        run: |
          case "${{ github.event.inputs.environment }}" in
            etnaqa)
              echo "path=tenants/etna/pr" >> $GITHUB_ENV
              ;;
            uat)
              echo "path=tenants/uat" >> $GITHUB_ENV
              ;;
            sandbox)
              echo "path=tenants/usds" >> $GITHUB_ENV
              ;;
            etnadev)
              echo "path=tenants/etna/qa" >> $GITHUB_ENV
              ;;
            knoxdev)
              echo "path=tenants/knox/dev" >> $GITHUB_ENV
              ;;
            demostage)
              echo "path=tenants/demostore/" >> $GITHUB_ENV
              ;;
          esac

      - name: Verify environment path
        run: echo "Selected path is ${{ env.path }}"
        
      - name: Checkout Code
        uses: actions/checkout@v2
        with: 
          ref: master

      - name: Kubernetes Set up
        uses: azure/k8s-set-context@v1
        with:
            kubeconfig: ${{ secrets.KUBECONFIG}}
            version: '1.19.9'

      - name: delete existing ssl kubernetes secret
        run: |
            ls -ltr
            pwd
            kubectl delete secret amla-pfx-secret -n znode
            kubectl delete secret amla-ssl-secret -n znode
            kubectl delete secret amla-tls-secret -n znode

      - name: amla-pfx-secret
        working-directory: ssl
        run: kubectl create secret generic amla-pfx-secret --from-file=amla.io.pfx --from-literal=password=${{ secrets.PFXSECRET }} -n znode

      - name: amla-ssl-secret  
        working-directory: ssl
        run: kubectl create secret generic amla-ssl-secret --from-file=amla.io.crt --from-file=amla.io.key -n znode

      - name: amla-tls-secret 
        working-directory: ssl
        run: kubectl create secret tls amla-tls-secret --cert=amla.io.crt --key=amla.io.key -n znode

      # - name: amla-tls-secret 
      #   working-directory: ssl_2024_25
      #   run: kubectl create secret tls sectigo-tls-secret --cert=sectigo.crt --key=sectigo.key -n znode

      # - name: amla-ssl-secret  
      #   working-directory: ssl_2024_25
      #   run: kubectl create secret generic sectigo-ssl-secret --from-file=amla.io.crt --from-file=amla.io.key -n znode

      # - name: delete pods
      #   working-directory: ${{ env.path }}
      #   run: kubectl delete -f deploy/app/pods -n znode

      # - name: re-create configmap
      #   working-directory: ${{ env.path }}
      #   run: |
      #     ls -ltr
      #     kubectl delete -f configmap -n znode
      #     kubectl create -f configmap -n znode
                      
      # - name: create pods
      #   working-directory: ${{ env.path }}
      #   run: kubectl create -f deploy/app/pods -n znode
