name: Sync ACR Images To Central India
on:
  workflow_dispatch:
    inputs:
      source_acr:
        description: 'Source ACR name (e.g., mysourceacr)'
        required: true
        type: string
      destination_acr:
        description: 'Destination ACR name (e.g., mydestacr)'
        required: true
        type: string
      syncqaimage:
        description: 'Sync z10-qa tag?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      syncstageimage:
        description: 'Sync latest z10-st* tag?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      syncsanboximage:
        description: 'Sync latest sandbox images'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
jobs:
  sync-images:
    runs-on: ubuntu-latest

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
         creds: ${{ github.event.inputs.syncsanboximage == 'true' && secrets.AZURE_CREDENTIALS_PROD_ADMIN || secrets.AZURE_CREDENTIALS_NP }}

    - name: Get Repositories from Source ACR
      id: get_repos
      run: |
        echo "Fetching repositories from ${{ github.event.inputs.source_acr }}"
        REPOS=$(az acr repository list --name ${{ github.event.inputs.source_acr }} --output tsv || echo "")
        echo "REPOS<<EOF" >> $GITHUB_ENV
        echo "$REPOS" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Sync Selected Tags
      run: |
        for repo in $REPOS; do
          echo "📂 Repo: $repo"

          # Safely get all tags for the repo
          tags=$(az acr repository show-tags \
            --name ${{ github.event.inputs.source_acr }} \
            --repository "$repo" \
            --output tsv || echo "")

          # Sync z10-qa tag
          if [[ "${{ github.event.inputs.syncqaimage }}" == "true" ]]; then
            echo "🔍 Checking for 'z10-qa' in $repo..."
            if echo "$tags" | grep -q "^z10-qa$"; then
              src_image="${{ github.event.inputs.source_acr }}.azurecr.io/$repo:z10-qa"
              dst_image="$repo:z10-qa"
              echo "🚀 Importing $src_image to ${{ github.event.inputs.destination_acr }}.azurecr.io/$dst_image"

              az acr import \
                --name ${{ github.event.inputs.destination_acr }} \
                --source "$src_image" \
                --image "$dst_image" \
                --force || echo "⚠️ Failed to import z10-qa for $repo"

              echo "✅ Synced z10-qa for $repo"
            else
              echo "⚠️ z10-qa not found in $repo"
            fi
          fi

          # Sync latest v10.* tag
          if [[ "${{ github.event.inputs.syncstageimage }}" == "true" ]]; then
            echo "🔍 Checking for v10.* tags in $repo..."
          
            v10_tags=$(az acr repository show-tags \
              --name ${{ github.event.inputs.source_acr }} \
              --repository "$repo" \
              --orderby time_desc \
              --output tsv 2>/dev/null | grep '^v10\.' || echo "")
          
            if [ -n "$v10_tags" ]; then
              latest_v10_tag=$(echo "$v10_tags" | head -n 1)
              echo "📦 Latest v10.* tag: $latest_v10_tag"
          
              src_image="${{ github.event.inputs.source_acr }}.azurecr.io/$repo:$latest_v10_tag"
              dst_image="$repo:$latest_v10_tag"
          
              echo "🚀 Importing $src_image to ${{ github.event.inputs.destination_acr }}.azurecr.io/$dst_image"
          
              az acr import \
                --name ${{ github.event.inputs.destination_acr }} \
                --source "$src_image" \
                --image "$dst_image" \
                --force || echo "⚠️ Failed to import $latest_v10_tag for $repo"
          
              echo "✅ Synced $latest_v10_tag for $repo"
            else
              echo "⚠️ No v10.* tags found in $repo"
            fi
          fi
          
          # Sync latest v* tag
          if [[ "${{ github.event.inputs.syncsanboximage }}" == "true" ]]; then
            echo "🔍 Checking for v* tags in $repo..."

            v_tags=$(az acr repository show-tags \
              --name ${{ github.event.inputs.source_acr }} \
              --repository "$repo" \
              --orderby time_desc \
              --output tsv 2>/dev/null | grep '^v' || echo "")

            if [ -n "$v_tags" ]; then
              latest_v_tag=$(echo "$v_tags" | head -n 1)
              echo "📦 Latest v* tag: $latest_v_tag"

              src_image="${{ github.event.inputs.source_acr }}.azurecr.io/$repo:$latest_v_tag"
              dst_image="$repo:$latest_v_tag"

              echo "🚀 Importing $src_image to ${{ github.event.inputs.destination_acr }}.azurecr.io/$dst_image"

              az acr import \
                --name ${{ github.event.inputs.destination_acr }} \
                --source "$src_image" \
                --image "$dst_image" \
                --force || echo "⚠️ Failed to import $latest_v_tag for $repo"

              echo "✅ Synced $latest_v_tag for $repo"
            else
              echo "⚠️ No v* tags found in $repo"
            fi
          fi

          echo "------"
        done
