name: Terraform Cloudflare DNS Management

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - DEV-1197-Automation-Task

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./Terraform  

      - name: Terraform Plan
        run: terraform plan -input=false -var "cloudflare_api_token1=${{ secrets.CLOUDFLARE_API_TOKEN1 }}" -var "cloudflare_zone_id1=${{ secrets.CLOUDFLARE_ZONE_ID1 }}"
        working-directory: ./Terraform 

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve -var "cloudflare_api_token1=${{ secrets.CLOUDFLARE_API_TOKEN1 }}" -var "cloudflare_zone_id1=${{ secrets.CLOUDFLARE_ZONE_ID1 }}"
        working-directory: ./Terraform  
