name: Run Shell Script via API To Update Admin Media Setting

on:
  workflow_dispatch:
    inputs:
      API_URL:
        description: 'API URL for the Media Configuration Update'
        required: true
      SECRET_KEY:
        description: 'Secret Key'
        required: true
      ACCESS_KEY:
        description: 'Access Key'
        required: true
      BUCKET_NAME:
        description: 'Bucket Name'
        required: true
      CDN_URL:
        description: 'CDN URL'
        required: true

jobs:
  run-shell-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "API_URL=${{ github.event.inputs.API_URL }}" >> $GITHUB_ENV          
          echo "SECRET_KEY=${{ github.event.inputs.SECRET_KEY }}" >> $GITHUB_ENV
          echo "ACCESS_KEY=${{ github.event.inputs.ACCESS_KEY }}" >> $GITHUB_ENV
          echo "BUCKET_NAME=${{ github.event.inputs.BUCKET_NAME }}" >> $GITHUB_ENV
          echo "CDN_URL=${{ github.event.inputs.CDN_URL }}" >> $GITHUB_ENV

      - name: Debug Environment Variables (Avoid exposing sensitive values)
        run: |
          echo "API_URL=${{ env.API_URL }}"
          echo "SECRET_KEY=***"
          echo "ACCESS_KEY=***"
          echo "BUCKET_NAME=${{ env.BUCKET_NAME }}"
          echo "CDN_URL=***"

      - name: Install Curl (if not installed)
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: List files in shellscript directory
        run: ls -l shellscript/

      - name: Make the shell script executable
        run: chmod +x shellscript/update_admin_media_setting.sh

      - name: Execute the Shell Script
        run: |
          bash shellscript/update_admin_media_setting.sh
