---
apiVersion: v1
kind: Service
metadata:
  annotations:
    znodekube.version: "10.0"
  creationTimestamp: null
  labels:
    io.znodekube.service: znode10customapi-artifi
    service: znode10customapi-artifi
  name: znode10customapi-artifi
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  type: ClusterIP
  selector:
    service: znode10customapi-artifi
