---
apiVersion: v1
kind: Service
metadata:
  annotations:
    znodekube.version: "10.0"
  creationTimestamp: null
  labels:
    io.znodekube.service: znode10xwebstore-artifi-app
    service: znode10xwebstore-artifi-app
    app: znode10xwebstore-artifi-app
  name: znode10xwebstore-artifi
spec:
  ports:
  - name: "webstorehttpsport"
    port: 443
    targetPort: 443
  type: ClusterIP
  selector:
    app: znode10xwebstore-artifi-app
