apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
  - ReadWriteOnce # Azure Disks do NOT support ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: azure-disk-sc # Use the correct StorageClass
