---  
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:    
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yml -o kube-compose.yml
    kompose.version: 1.28.0 (c4137012e) 
  name: znode10xadmin-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: znode10xadmin
  minReplicas: 1 
  maxReplicas: 2 
  metrics:
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource 
    resource:
      name: memory 
      target:
        type: Utilization
        averageUtilization: 80 
 
---  
