global:
  scheduler:
    enabled: true
    schedule: "0 7 * * *" # UTC time → 2:00 AM CST / 12:30 PM IST
    targetDeployments:
      - znode10xapi
      - znode10xadmin
      - znode10xapiv2
      - znode10xapicp
      - znode10xwebstore
      - znode10xapigateways    
resources:
  znode10xpluginspreedly:
    configmap:
      Spreedly__EnvironmentKey: "7HSS3HGTS88NQRRHK9ES2DQ1WA"