name: Flexible Branch Upmerge

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source branch (e.g., int, qat)'
        required: true
        default: 'int'
      target_branch:
        description: 'Target branch (e.g., qat, stage)'
        required: true
        default: 'qat'

jobs:
  upmerge:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [znode10-api-migration, znode10-admin-migration]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: MRRSoft/${{ matrix.repo }}
          token: ${{ secrets.ACCESS_REPO }}

      - name: Check if target branch exists
        id: check_target
        run: |
          if git ls-remote --exit-code --heads origin ${{ github.event.inputs.target_branch }}; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Merge source into target
        if: steps.check_target.outputs.exists == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git fetch origin ${{ github.event.inputs.source_branch }}
          git fetch origin ${{ github.event.inputs.target_branch }}

          git checkout ${{ github.event.inputs.target_branch }}
          git merge origin/${{ github.event.inputs.source_branch }} -m "Automated upmerge from ${{ github.event.inputs.source_branch }} into ${{ github.event.inputs.target_branch }}"
          git push origin ${{ github.event.inputs.target_branch }}
        continue-on-error: true

      - name: Notify Google Chat on failure
        if: failure()
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            --data '{"text": "❌ Upmerge failed from `${{ github.event.inputs.source_branch }}` to `${{ matrix.repo }}/${{ github.event.inputs.target_branch }}`. Please check for conflicts."}' \
            ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
