name: Onboard Local Dev Environments using helm

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: Select the environment
        required: true


jobs:
  restart_deployments:
    name: Restart Selected Deployments
    runs-on: [self-hosted, build-runner-100.188]
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Kubernetes Set up
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.2    

      - name: Helm Install Ingress
        working-directory: znode10-helm
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm upgrade --install nginx ingress-nginx/ingress-nginx \
            --namespace znode \
            --set controller.kind=DaemonSet \
            --set controller.hostNetwork=true \
            --set controller.daemonset.useHostPort=true \
            --set controller.service.type=ClusterIP \
            --set controller.admissionWebhooks.enabled=false \
            --set controller.ingressClass=nginx \
            --set controller.ingressClassResource.name=nginx \
            --set controller.ingressClassResource.enabled=true

      - name: Helm Install or Upgrade Znode10x helm
        working-directory: znode10-helm
        run: |
          echo "Deploying to environment: ${{ github.event.inputs.environment }}"
          helm upgrade --install znode10x . \
            -f default-values.yml \
            -f values.yml \
            -f "${{ github.event.inputs.environment }}-values.yml" \
            -f ingress-values.yml \
            --set global.tenant=z10 \
            --set global.environment=${{ github.event.inputs.environment }} \
            --set global.imageTag=z10-${{ github.event.inputs.environment }} \
            --set global.domain=amla.io \
            --set global.imageRegistry=acrznodedv.azurecr.io \
            --namespace znode
          
          kubectl rollout restart daemonset nginx-ingress-nginx-controller -n znode