global:
  timezone: Asia/Kolkata  

resources:
  znode10xadmin:
    configmap:
      appsettings__IsLocalEnvironment: "true"

  znode10xapi:
    configmap:
      appsettings__IsLocalEnvironment: "true"
      ElasticSearchApiRootUri: "https://utility-z10-dev8.amla.io"

  znode10xcustomtable:
    configmap:
      appsettings__IsLocalEnvironment: "true"  

scheduler:
  enabled: true # Set to true per env when needed
  # Schedule time: 3:00 AM UTC
  # Equivalent IST (India Standard Time): 8:30 AM IST
  # Equivalent ET  (Eastern Time):        11:00 PM ET (previous day, during DST)
  # schedule: "0 3 * * *"
  schedule: "30 13 * * *" # LOCAL VM IST
  targetDeployments:
  - znode10xapi
  - znode10xadmin
  - znode10xapiv2
  - znode10xapicp
  - znode10xwebstore
  - znode10xapigateways

resources:
  znode10xdiagnostic:
    enableService: true
    serviceType: ClusterIP
    port: 80
    minReplicas: 1
    maxReplicas: 1
    replicaCount: 1
    image:
      name: znode10xdiagnostic
      pullPolicy: Always
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    configmap:
      ASPNETCORE_HTTPS_PORT: http://+:80
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__Sql: "{{ .Values.global.db.wbst_db }}"
      ConnectionStrings__RabbitMQ: "http://znode10xrabbitmq.{{ .Release.Namespace }}:15672"
      ConnectionStrings__Elasticsearch: "http://znode10xelasticsearch.{{ .Release.Namespace }}.svc.cluster.local:9200"
      ConnectionStrings__Redis: "redisapi-headless.{{ .Release.Namespace }}:26379,serviceName=mymaster,allowAdmin=True"
      MongoDB__ConnectionString: "mongodb://znode10xmongodb.{{ .Release.Namespace }}:27017/Znode_10xFeature_Docker_LogMessage"
      ServiceUrls__HealthCheckBaseUrl: "https://diagnostic{{ $.Values.global.domain }}/"
      LoginCredentials__Username: "admin@znode.com"
      LoginCredentials__Password: "Admin@#765"
      APIHealthCheckEndPoint: |
        [
         { "Name": "API Gateways", "Url": "http://znode10xapigateways.{{ .Release.Namespace }}.svc.cluster.local/health" },
         { "Name": "Admin Panel", "Url": "https://admin{{ $.Values.global.domain }}/health" },
         { "Name": "Webstore", "Url": "https://webstore{{ $.Values.global.domain }}/health" },
         { "Name": "API V1", "Url": "http://znode10xapi.{{ .Release.Namespace }}.svc.cluster.local/health" },
         { "Name": "API V2", "Url": "http://znode10xapiv2.{{ .Release.Namespace }}.svc.cluster.local/health" },
         { "Name": "Commerce Portal API", "Url": "http://znode10xapicp.{{ .Release.Namespace }}.svc.cluster.local/health" },
         { "Name": "CustomAPI", "Url": "http://znode10xcustomapi.{{ .Release.Namespace }}.svc.cluster.local/health" },
         { "Name": "CustomTable", "Url": "http://znode10xcustomtable.{{ .Release.Namespace }}.svc.cluster.local/health" },
         { "Name": "PageBuilder", "Url": "https://pagebuilder{{ $.Values.global.domain }}/health" },
         { "Name": "PaymentManager", "Url": "http://znode10xpaymentmanager.{{ .Release.Namespace }}.svc.cluster.local/health" },
         { "Name": "PluginBrainTree", "Url": "http://znode10xpluginbraintree.{{ .Release.Namespace }}.svc.cluster.local/health" },
         { "Name": "PluginFedex", "Url": "http://znode10xpluginfedex.{{ .Release.Namespace }}.svc.cluster.local/health" },
         { "Name": "PluginServer", "Url": "https://pluginserver.{{ .Release.Namespace }}.com/health" },
         { "Name": "PluginSpreedly", "Url": "http://znode10xpluginspreedly.{{ .Release.Namespace }}.svc.cluster.local/health" },
         { "Name": "PluginUPS", "Url": "http://znode10xpluginups.{{ .Release.Namespace }}.svc.cluster.local/health" },
         { "Name": "Reports", "Url": "http://znode10xreports.{{ .Release.Namespace }}.svc.cluster.local/health" },
         { "Name": "ShippingManager", "Url": "http://znode10xshippingmanager.{{ .Release.Namespace }}.svc.cluster.local/health" },
         { "Name": "TaxManager", "Url": "http://znode10xtaxmanager.{{ .Release.Namespace }}.svc.cluster.local/health" }
        ]

  znode10xwebstore:
    configmap:
      REDIS_SENTINEL_ENABLED: "true"

  znode10xutility:
    configmap: 
      DB_NAME: "z10_wbst_dev8"             
