---
# templates/configmap.yaml
{{- range $name, $svc := .Values.resources }}
{{- if and ($svc.enableService | default false) }}
  {{- $cfg := get $svc "configmap" }}
  {{- if and (typeIs "map[string]interface {}" $cfg) (gt (len $cfg) 0) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-configmap
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $name }}
    service: {{ $name }}
data:
{{- range $key, $val := $cfg }}
  {{ $key }}: {{ tpl $val $ | quote }}
{{- end }}
{{- if and $.Values.global.newrelic.enabled (ne $.Values.global.newrelic.licensekey "") }}
  NEW_RELIC_LICENSE_KEY: {{ $.Values.global.newrelic.licensekey | quote }}
  NEW_RELIC_LABELS: "Tenant:{{ upper $.Values.global.tenant }};Environment:{{ upper $.Values.global.environment }}"
  NEW_RELIC_APP_NAME: "{{ upper $name }}-{{ upper $.Values.global.tenant }}-{{ upper $.Values.global.environment }}"
{{- end }}
---
  {{- end }}
{{- end }}
{{- end }}

