{{- range $name, $svc := .Values.resources }}
{{- if and ($svc.enableService | default true) (eq $svc.kind "StatefulSet") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{ include "znode10-helm-db.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app: {{ $name }}
  annotations:
    meta.helm.sh/release-name: {{ $.Release.Name }}
    meta.helm.sh/release-namespace: {{ $.Release.Namespace }}
spec:
  type: {{ $svc.serviceType | default "ClusterIP" }}
  selector:
    app: {{ $name }}
  ports:
  {{- range $svc.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
  {{- end }}
---
{{- end }}
{{- end }}
