name: Merge int into team branches

on:
  workflow_dispatch:       # Allow manual trigger

jobs:
  merge-int:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [znode10-api-migration, znode10-admin-migration] # Add your repos here
        target_branch: [dev1, dev2, dev3,dev4,dev5,dev6] # List of team branches
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: MRRSoft/${{ matrix.repo }}
          token: ${{ secrets.ACCESS_REPO }}

      - name: Check if target branch exists
        id: check_branch
        run: |
          if git ls-remote --exit-code --heads origin ${{ matrix.target_branch }}; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Merge int into target branch
        if: steps.check_branch.outputs.exists == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git fetch origin int
          git fetch origin ${{ matrix.target_branch }}

          git checkout ${{ matrix.target_branch }}
          git merge origin/int -m "Automated merge from int into ${{ matrix.target_branch }}"
          git push origin ${{ matrix.target_branch }}
        continue-on-error: true

      - name: Notify Google Chat on failure
        if: failure()
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            --data '{"text": "❌ Merge failed from `int` to `${{ matrix.repo }}/${{ matrix.target_branch }}`. Please check for conflicts."}' \
            ${{ secrets.DEPLOYMENT_ALERTS }}
