name: Trigger - Z10 HTFX

on:
  workflow_dispatch:
    inputs:
      tenant:
        description: Tenant name
        required: true
        default: z10
        type: choice
        options:
          - z10

      environment:
        description: Target environment (e.g., dev1, dev2, etc.)
        required: true
        default: htfx
        type: choice
        options:
          - htfx
      branch:
        description: Git branch to deploy
        required: true
        default: hotfixes
      namespace:
        description: Target namespace (e.g., znode, dev1)
        required: true
        default: znode
      services:
        description: Services to Build and Deploy
        required: true
        default: '{"wbst": false, "pgbld": false, "admin": false, "api": false, "gateway": false, "customtable": false, "v2": false, "a-commerce": true, "portal": false, "cstm": false, "paymngr": false, "spreedly": false, "braintree": false, "reports": false, "shipping": false, "fedex": false, "ups": false, "azfunction": false, "graphqlapi": false, "taxmanager": false, "avatax": false, "plugin": false,  "cc-api": false, "cc-admin": false}'
        type: string

      db_deploy:
        description: "Deploy all DB"
        type: boolean
        required: true
        default: false

      all:
        description: Deploy all services
        required: false
        default: false
        type: boolean

      release_version_number:
        description: "Current Release version"
        required: true
        type: string
        
      version:
        description: Version for all selected services
        required: true
        default: "v10.2.1.3"
        type: string
        
jobs:
  trigger-build-deploy:
    uses: ./.github/workflows/build-deploy.yaml
    with:
      tenant: ${{ inputs.tenant }}
      environment: ${{ inputs.environment }}
      branch: ${{ inputs.branch }}
      namespace: ${{ inputs.namespace }}
      services: ${{ inputs.services }}
      all: ${{ inputs.all }}
      triggered_by: ${{ github.actor }}
      release_version_number: ${{ inputs.release_version_number }}
      version: ${{ inputs.version }}      
    secrets: inherit

  trigger-db-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.db_deploy == 'true' }}
    steps:
      - name: Trigger DB Deployment Pipeline
        env:
          GH_TOKEN: ${{ secrets.ACCESS_REPO }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/repos/MRRSoft/znode10-teams-devops/actions/workflows/db_deploy_azure_st_htfx.yml/dispatches \
            -d @- <<EOF
          {
            "ref": master,
            "inputs": {
              "environment": "${{ github.event.inputs.environment }}",
              "branch": "${{ github.event.inputs.branch }}",
              "multifront_db": "true",
              "hangfire_db": "true",
              "recommendation_db": "true",
              "payment_manager_db": "true"
            }
          }
          EOF
