apiVersion: v1
kind: Service
metadata:
  annotations:
    znodekube.version: "10.0"
  creationTimestamp: null
  labels:
    app: znode10xredis
  name: znode10xredis
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  - name: "8001"
    port: 8001
    targetPort: 8001
  type: ClusterIP
  selector:
    app: znode10xredis
status:
  loadBalancer: {}

