apiVersion: v1
kind: ConfigMap
metadata:
  name: znode10customapi-config
data:
  TZ: "America/New_York"
  ASPNETCORE_HTTPS_PORT: "https://+:443"
  ASPNETCORE_Kestrel__Certificates__Default__Password: "Amla@987"
  ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/pfx/amla.io.pfx"
  ASPNETCORE_URLS: "https://+:443;http://+:80"
  appsettings__PluginApiRootUri: "https://pluginserver.znode.com"
  appsettings__PaymentApplicationUrl: "https://https://paymentapi.znode10training.com"
  appsettings__ZnodeApiRootUri: "https://https://api.znode10training.com/"
  appsettings__ZnodeApiGateway: "https://apigateway.znode10training.com"
  appsettings__ZnodePaymentApiDomainName: "paymentapi.znode10training.com"
  appsettings__EnableTokenBasedAuthorization: "false"
  