apiVersion: v1
kind: ConfigMap
metadata:
  name: znode10xcustomtable-config
data:
  TZ: "America/New_York"
  ASPNETCORE_HTTPS_PORT: "https://+:443"
  ASPNETCORE_Kestrel__Certificates__Default__Password: "Amla@987"
  ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/pfx/amla.io.pfx"
  ASPNETCORE_URLS: "https://+:443;http://+:80"
  ASPNETCORE_CULTURE: "en_US.UTF-8"
  ASPNETCORE_UI_CULTURE: "en_US.UTF-8"
  ConnectionStrings__ZnodeCustomTableEntities: "Server=tcp:db-znode10x-production-ep.database.windows.net,1433;Initial Catalog=wbst_z10_trng;Persist Security Info=False;User ID=admin-db-znode10x-prod-ep;Password=elPL_Ro@9#701;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
  ConnectionStrings__ZnodeFramework_Entities: "Server=tcp:db-znode10x-production-ep.database.windows.net,1433;Initial Catalog=wbst_z10_trng;Persist Security Info=False;User ID=admin-db-znode10x-prod-ep;Password=elPL_Ro@9#701;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
  ConnectionStrings__Znode_Entities: "Server=tcp:db-znode10x-production-ep.database.windows.net,1433;Initial Catalog=wbst_z10_trng;Persist Security Info=False;User ID=admin-db-znode10x-prod-ep;Password=elPL_Ro@9#701;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
  ConnectionStrings__ZnodeMongoDBForLog: "mongodb://znode10xmongodb.znode:27017/Znode_10xFeature_Docker_LogMessage"
  ConnectionStrings__Znode_Entities_CustomSP: "Server=tcp:db-znode10x-production-ep.database.windows.net,1433;Initial Catalog=wbst_z10_trng;Persist Security Info=False;User ID=admin-db-znode10x-prod-ep;Password=elPL_Ro@9#701;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
  ConnectionStrings__ZnodeCustomStoreProcedureDB: "Server=tcp:db-znode10x-production-ep.database.windows.net,1433;Initial Catalog=wbst_z10_trng;Persist Security Info=False;User ID=admin-db-znode10x-prod-ep;Password=elPL_Ro@9#701;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"