apiVersion: v1
kind: ConfigMap
metadata:
  name: znode10xwebstore-config
data:
  PORT: "443"
  NEXTAUTH_URL: "https://hardware.znode10training.com/"
  NEXTAUTH_SECRET: "authentication"
  HTTPS: "true"
  SSL_CRT_FILE: "/app/ssl/amla.io.crt"
  SSL_KEY_FILE: "/app/ssl/amla.io.key"
  BASE_URL: "https://apigateway.znode10training.com/"
  CONTENT_SECURITY_POLICY: "script-src blob: 'self' https://*.paypal.com https://*.paypal.cn https://*.paypalobjects.com https://objects.paypal.cn https://www.gstatic.com https://*.google.com https://*.synchronycredit.com https://synchronycredit.com https://www.googleadservices.com https://static-na.payments-amazon.com https://payments-amazon.com www.googletagmanager.com https://payments-sandbox.amazon.com https://znode10x.azureedge.net/ https://*.google.com/ https://*.znode10training.com/ *.google-analytics.com *.osano.com *.jsdelivr.net *.authorize.net *.cybersource.com *.braintreegateway.com *.googleapis.com 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https://payments.amazon.com/ https://apay-us.amazon.com/ https://payments-sandbox.amazon.com/ https://static-na.payments-amazon.com/ https://www.google-analytics.com/ https://tattle.api.osano.com/ https://consent.api.osano.com https://znode10x.azureedge.net/ https://*.znode10training.com/ *.braintreegateway.com *.braintree-api.com *.googleapis.com 'unsafe-inline' 'unsafe-eval'; frame-ancestors 'self' https://portal.tradecentric.com https://*.znode10training.com https://*.authorize.net https://*.amazon.com;"
  #X_FRAME_OPTION: "ALLOW-FROM https://admin.znode10training.com/,https://portal.tradecentric.com,https://hardware.znode10training.com,https://academy-store-preview.znode10training.com,https://academy-store.znode10training.com"
  ALLOW_REFERRER: "https://admin.znode10training.com/,https://portal.tradecentric.com/,https://hardware.znode10training.com/,https://test.authorize.net/,https://apay-us.amazon.com/,https://academy-store-preview.znode10training.com/,https://academy-store.znode10training.com/"
  X_CONTENT_TYPE_OPTIONS: "nosniff"
  PERMISSIONS_POLICY: "camera=(self), fullscreen=(self), geolocation=(self)"
  REFERRER_POLICY: "strict-origin-when-cross-origin"
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
  MONGO_DB: "Znode_10xFeature_Docker_LogMessage"
  MONGO_URL: "mongodb://znode10xmongodb.znode:27017/Znode_10xFeature_Docker_LogMessage"
  CACHE_TOKEN: ""
  APPLICATION_INSIGHT_CONNECTION_STRING: ""
  APPLICATION_INSIGHT: "false"
  ENABLE_CACHE: "true"
  REDIS_CONNECTION_STRING: "redis://znode10redistrng.znode:6379"
  PAYMENT_DOMAIN_NAME: "https://paymentapi.znode10training.com/"
  DEFAULT_THEME: "B2B_B2B"
  CACHE_KEY: ""
  REVALIDATE_URL: "/api/revalidate/"
  IS_MESSAGE_BROKER_REGISTERED: "false"
  PaymentAPI_PrivateKey: "432915F1-17ee-d018-a005-a14-61be3e94a83e"
  API_Domain_Key: "a2c32d26-fb56-4e2d-aa44-10ae401a0970"
  API_Domain: "false"
  FACEBOOK_CLIENT_SECRET: "2cf9bcd34d337fb65a10342f2e8a7f67"
  FACEBOOK_CLIENT_ID: "1411075839811952"
  GOOGLE_CLIENT_SECRET: "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"
  GOOGLE_CLIENT_ID: "103018173439-tbuo5188fqbgu3tjipo9kqfv5ibbcgpt.apps.googleusercontent.com"
  API: "https://hardware.znode10training.com"
  MONGO: "mongodb://znode10xmongodb.znode:27017/Znode_10xFeature_Docker_LogMessage"
  ENABLE_LOGGING: "true"
  WEBSTORE_DOMAIN_NAME: "hardware.znode10training.com"
  BASE_API_URL: "https://apigateway.znode10training.com/"
  NODE_ENV: "production"
