apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
spec:
  capacity:
    storage: 50Gi # Set appropriate storage capacity
  accessModes:
  - ReadWriteMany
  azureFile:
    secretName: znode10storage # Your storage account secret
    shareName: z10-elasticfileshare1
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: "" # Leave blank if binding to the manually created PV
