global:
  timezone: Asia/Kolkata

resources:
  znode10xadmin:
    configmap:
      appsettings__IsLocalEnvironment: "true"

  znode10xapi:
    configmap:
      appsettings__IsLocalEnvironment: "true"

  znode10xcustomtable:
    configmap:
      appsettings__IsLocalEnvironment: "true"

  znode10xwebstore:
    configmap:
      REDIS_SENTINEL_ENABLED: "true"   

  znode10xutility:
    configmap: 
      DB_NAME: "z10_wbst_dev1"         
