{{- if and (eq $.Values.global.tenant "z10") (eq $.Values.global.environment "qa") (hasKey .Values.resources "znode10xpluginserver") (.Values.resources.znode10xpluginserver.enableService | default true) }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: znode10-plugin-server-pv
  namespace: {{ $.Release.Namespace }}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-fuse-premium
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: znode10-plugin-server-handle
    volumeAttributes:
      containerName: z10-plugin
      storageAccount: strz10qa
    nodeStageSecretRef:
      name: znode10storage
      namespace: {{ $.Release.Namespace }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: znode10-plugin-server-pvc
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azureblob-fuse-premium
  resources:
    requests:
      storage: 5Gi
  volumeName: znode10-plugin-server-pv

{{- end }}
