{{- if and (eq $.Values.global.tenant "z10") (eq $.Values.global.environment "dev2") }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  namespace: {{ $.Release.Namespace }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/Data/storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: znode10xmedia-pvc
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: media-pv
{{- end }}