---  
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:    
    znodekube.version: "10.0"  
  name: znode10xadmin-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: znode10xadmin
  minReplicas: 1 
  maxReplicas: 1 
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: znode10xadmin
      target:
        type: Utilization
        averageUtilization: 80
  - type: ContainerResource 
    containerResource:
      name: memory
      container: znode10xadmin
      target:
        type: Utilization
        averageUtilization: 80 
 
---  

