apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: znode-deployment-restart-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch"]