---
apiVersion: v1
kind: Service
metadata:
  annotations:    
    znodekube.version: "10.0"
  creationTimestamp: null
  labels:
    io.znodekube.service: znode10xelasticsearch
  name: znode10xelasticsearch
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
  selector:
    io.znodekube.service: znode10xelasticsearch
status:
  loadBalancer: {}

---

