apiVersion: v1
kind: Service
metadata:
  annotations:
    znodekube.version: "10.0"
  creationTimestamp: null
  labels:
    service: znode10redisdevknox
  name: znode10redisdevknox
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
    - name: "8001"
      port: 8001
      targetPort: 8001 
  type: LoadBalancer
  selector:
    app: znode10redisdevknox
status:
  loadBalancer: {}

