--- 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    znodekube.version: "10.0"  
  name: znode10apicp-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: znode10apicp
  minReplicas: 1 
  maxReplicas: 4
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: znode10apicpcontainer
      target:
        type: Utilization
        averageUtilization: 90
  - type: ContainerResource 
    containerResource:
      name: memory
      container: znode10apicpcontainer
      target:
        type: Utilization
        averageUtilization: 90 
          
---
