apiVersion: v1
kind: PersistentVolume
metadata:
  name: znode10x-elasticsearch-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: azurefile
  azureFile:
    secretName: znode10storage
    shareName: elasticsearch
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: znode10x-elasticsearch-pvc
  namespace: znode
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azurefile
  resources:
    requests:
      storage: 10Gi

---