---
apiVersion: v1
kind: Service
metadata:
  annotations:    
    znodekube.version: "10.0"
  creationTimestamp: null
  labels:
    io.znodekube.service: znode10xmongodb
  name: znode10xmongodb
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.znodekube.service: znode10xmongodb
status:
  loadBalancer: {}

--- 

