---
apiVersion: v1
kind: Service
metadata:
  annotations:
    znodekube.version: "10.0"
  creationTimestamp: null
  labels:
    service: znode10xshippingmanager
  name: znode10xshippingmanager
spec:
  ports:
    - name: "shippingmanagerhttpport"
      port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    service: znode10xshippingmanager


---