apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: znode10x-redis-pv
spec:
  storageClassName: azureblob-nfs-premium
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany 
  csi:
    driver: blob.csi.azure.com
    readOnly: false  
    volumeHandle: znode10redisuat
    volumeAttributes:  
      storageAccount: growdevstorage  
      containerName: z10-redis
    nodeStageSecretRef:
      name: znode10storage
      namespace: znode
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: znode10-redis-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: azureblob-nfs-premium
  volumeName: znode10x-redis-pv
