--- 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    znodekube.version: "10.0"  
  name: znode10xpluginups-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: znode10xpluginups
  minReplicas: 1 
  maxReplicas: 2 
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: znode10xpluginups
      target:
        type: Utilization
        averageUtilization: 80
  - type: ContainerResource 
    containerResource:
      name: memory
      container: znode10xpluginups
      target:
        type: Utilization
        averageUtilization: 80 
          
---