
apiVersion: v1
kind: Service
metadata:
  annotations:
     kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yml -o kube-compose.yml
     kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    service: znode10xredis
  name: znode10xredis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
    - name: "8001"
      port: 8001
      targetPort: 8001 
  type: LoadBalancer
  selector:
    app: znode10xredis 
status:
  loadBalancer: {}
