apiVersion: v1
kind: Service
metadata:
  annotations:
    znodekube.version: "10.0"
  creationTimestamp: null
  labels:
    io.znodekube.service: znode10xpagebuilder
    service: znode10xpagebuilder
    app: znode10xpagebuilder
  name: znode10xpagebuilder
spec:
  ports:
  - name: "webstorehttpsport"
    port: 443
    targetPort: 443
  type: LoadBalancer
  selector:
    app: znode10xpagebuilder
status:
  loadBalancer: {}


---
