--- 
apiVersion: v1
kind: Service
metadata:
  annotations:
    znodekube.version: "10.0"
  creationTimestamp: null
  labels:
    service: znode10xapigateways
  name: znode10xapigateways
spec:
  ports:
    - name: "443"
      port: 443
      targetPort: 443 
  selector:
    service: znode10xapigateways
  type: LoadBalancer
status:
  loadBalancer: {}
---