apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: znode10x-mongo-pv
spec:
  storageClassName: azureblob-nfs-premium
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany 
  csi:
    driver: blob.csi.azure.com
    readOnly: false  
    volumeHandle: znode10xmongo
    volumeAttributes:  
      storageAccount: trngdev
      containerName: znode10-resources
    nodeStageSecretRef:
      name: znode10storage
      namespace: znode
  persistentVolumeReclaimPolicy: Retain
