---    
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:    
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yml -o kube-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  name: znode10redisusds-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: znode10redisusds
  minReplicas: 1 
  maxReplicas: 4 
  metrics:
    - type: Resource
      resource:
        name: cpu 
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource 
      resource:
        name: memory 
        target:
          type: Utilization
          averageUtilization: 80 
--- 

