name: Reusable Service Builder

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
      working_directory:
        required: true
        type: string
      compose_file:
        required: true
        type: string
      acr_server:
        required: true
        type: string
    secrets:
      access_token:
        required: true
      acr_username:
        required: true
      acr_password:
        required: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Service Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.access_token }}

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.acr_username }}
          password: ${{ secrets.acr_password }}
          registry: ${{ inputs.acr_server }}

      - name: Build and Push Docker Image
        working-directory: ${{ inputs.working_directory }}
        run: |
          echo "Tag=${{ github.run_id }}" > .env
          echo "AmlaRegistry=${{ inputs.acr_server }}" >> .env
          docker compose -f ${{ inputs.compose_file }} build --no-cache
          docker compose -f ${{ inputs.compose_file }} push --ignore-push-failures
