name: Build and Deploy Services

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Git branch to deploy"
        required: true
        default: "main"
      all:
        description: "Deploy all services"
        required: false
        default: false
        type: boolean
      services:
        description: "JSON of selected services"
        required: false
        default: '{"webstore": false, "admin": false, "api": false}'
        type: string

jobs:
  parse_services:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Generate Matrix
        id: set
        run: |
          ALL=${{ github.event.inputs.all }}
          SELECTED=$(echo '${{ github.event.inputs.services }}' | jq -r 'to_entries[] | select(.value == true) | .key' | tr '\n' ' ')
          CONFIG=$(cat .github/services-config.json)

          if [[ "$ALL" == "true" ]]; then
            FINAL="$CONFIG"
          else
            FINAL=$(echo "$CONFIG" | jq --argjson keys "$(echo $SELECTED | jq -R 'split(" ")')" '[.[] | select(.service as $s | $keys | index($s))]')
          fi

          echo "matrix=$(echo "$FINAL" | jq -c)" >> $GITHUB_OUTPUT

  build_services:
    needs: parse_services
    strategy:
      matrix:
        include: ${{ fromJson(needs.parse_services.outputs.matrix) }}
    uses: ./.github/workflows/build-service.yaml
    with:
      service: ${{ matrix.service }}
      repository: ${{ matrix.repository }}
      ref: ${{ github.event.inputs.branch }}
      working_directory: ${{ matrix.working_directory }}
      compose_file: ${{ matrix.compose_file }}
      acr_server: acrznodedv.azurecr.io
    secrets:
      access_token: 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
      acr_username: acrznodedv
      acr_password: R2FSmILZEEiqba1306gpaxsNV6Dn9rOYHf46Q5rj0L+ACRBTV+pr
