--- 
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yml -o kube-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    service: znode10xapiv2
  name: znode10xapiv2
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    service: znode10xapiv2
  type: ClusterIP

status:
  loadBalancer: {}
---