global:

scheduler:
  enabled: true # Set to true per env when needed
  # Schedule time: 3:00 AM UTC
  # Equivalent IST (India Standard Time): 8:30 AM IST
  # Equivalent ET  (Eastern Time):        11:00 PM ET (previous day, during DST)
  # schedule: "0 3 * * *"
  schedule: "30 07 * * *" # LOCAL VM IST
  targetDeployments:
  - znode10xapi
  - znode10xadmin
  - znode10xapiv2
  - znode10xapicp
  - znode10xwebstore
  - znode10xapigateways

resources:
  znode10xadmin:
    configmap:
      appsettings__IsLocalEnvironment: "true"

  znode10xapi:
    configmap:
      appsettings__IsLocalEnvironment: "true"
      appsettings__ZnodeCommercePortalRootUri: http://znode10xapicp.znode.svc.cluster.local

  znode10xcustomtable:
    configmap:
      appsettings__IsLocalEnvironment: "true"

  znode10xwebstore:
    configmap:
      REDIS_SENTINEL_ENABLED: "true"

  znode10xutility:
    configmap:
      DB_NAME: "z10_wbst_int"
