apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    znodekube.version: "10.0"
  name: znode10xapiv2-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: znode10xapiv2
  minReplicas: 4
  maxReplicas: 6
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: znode10xapiv2
      target:
        type: Utilization
        averageUtilization: 75
  - type: ContainerResource
    containerResource:
      name: memory
      container: znode10xapiv2
      target:
        type: Utilization
        averageUtilization: 75

---
