name: Trigger - Z10 DEV1

on:
  push:
    branches:
      - int
      - dev1
      - dev2
      - master
  pull_request:
    branches:
      - int
      - dev1
      - dev2
  workflow_dispatch:  # Keep manual trigger for emergencies
    inputs:
      tenant:
        description: Tenant name
        required: true
        default: z10
      environment:
        description: Target environment (e.g., dev1, dev2, etc.)
        required: true
        default: dev1
      branch:
        description: Git branch to deploy
        required: true
        default: master
      namespace:
        description: Target namespace (e.g., znode, dev1)
        required: true
        default: znode
      services:
        description: Services to Build and Deploy
        required: true
        default: '{"wbst": false, "pgbld": false, "admin": false, "api": false, "gateway": false, "customtable": false, "v2": false, "a-commerce": false, "portal": false, "cstm": false, "paymngr": false, "spreedly": false, "braintree": false, "reports": false, "shipping": false, "fedex": false, "ups": false, "azfunction": false, "graphqlapi": false, "taxmanager": false, "avatax": false, "diagno": false, "python": false, "cc-api": false, "cc-admin": false}'
        type: string
      all:
        description: Deploy all services
        required: false
        default: false
        type: boolean
      skip_security_scan:
        description: Skip security scanning (not recommended)
        required: false
        default: false
        type: boolean
      security_gate_enabled:
        description: Enable security gate (block deployment on critical issues)
        required: false
        default: true
        type: boolean

jobs:
  trigger-build-deploy:
    uses: ./.github/workflows/build-deploy-secure.yaml
    with:
      tenant: ${{ inputs.tenant }}
      environment: ${{ inputs.environment }}
      branch: ${{ inputs.branch }}
      namespace: ${{ inputs.namespace }}
      services: ${{ inputs.services }}
      all: ${{ inputs.all }}
      triggered_by: ${{ github.actor }}
      skip_security_scan: ${{ inputs.skip_security_scan }}
      security_gate_enabled: ${{ inputs.security_gate_enabled }}
    secrets: inherit