apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 20Gi # Set appropriate storage capacity
  accessModes:
  - ReadWriteMany
  azureFile:
    secretName: znode10storage # Your storage account secret
    shareName: z10-redisfileshare1 # Replace with your Redis file share name
    readOnly: false


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: "" # Leave blank if binding to the manually created PV
